server:
  port: 8080
  servlet: 
    charset : utf-8 #서블릿
    force : true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
    
  datasource:
    url: jdbc:h2:mem:bankdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: '' #DB 비밀번호 빈문자
  h2:
    console:
      enabled: true # H2 데이터 베이스 콘솔을 활성화 한다.